# Ci example
name: Environment example

on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    steps:
      - name: Get env Vars for Prod
        run: |
          echo "${{vars.ENV_VAR}}"
          